
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 19 15:08:35 CST 2017
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class TS {
  /* terminals */
  public static final int id = 7;
  public static final int arreglo = 2;
  public static final int puntopunto = 8;
  public static final int EOF = 0;
  public static final int num = 6;
  public static final int corchetec = 4;
  public static final int corchetea = 3;
  public static final int error = 1;
  public static final int ubicar = 5;
}

