/* The following code was generated by JFlex 1.6.1 */

package Analisis;
import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analisis/LexicoH.jflex</tt>
 */
public class LexicoH implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    52, 52, 52, 52, 52, 52, 52, 52, 52,  8,  7, 52,  8,  6, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
     8, 40, 50, 52, 41, 42, 36,  4, 47, 48, 33, 31, 49, 32,  5, 34, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 52, 52, 38, 39, 37, 52, 
    52, 21,  2, 20, 11, 19, 30, 28, 29, 24,  2,  2, 18,  9, 25, 10, 
    17, 14, 15, 13, 16, 22, 27,  2, 26,  2,  2, 43, 51, 44, 52,  3, 
    52, 21,  2, 20, 11, 19, 30, 28, 29, 24,  2,  2, 18,  9, 25, 10, 
    17, 14, 15, 13, 16, 22, 27,  2, 26,  2,  2, 45, 35, 46, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 
    52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52, 52
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\1\2\2\3\2\4\2\2\1\0\10\2"+
    "\1\0\1\2\1\5\1\6\1\7\1\10\2\3\1\11"+
    "\1\12\1\13\1\3\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\4\0"+
    "\1\2\1\0\2\2\1\0\11\2\1\0\1\2\1\0"+
    "\1\30\1\2\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\37\1\40\1\41\1\42\1\43\1\44\3\0"+
    "\1\45\2\46\1\0\2\2\1\47\1\0\1\47\4\2"+
    "\1\50\1\51\1\2\1\0\1\2\1\52\1\0\2\2"+
    "\2\53\1\0\1\2\3\0\2\54\1\55\2\56\1\2"+
    "\1\57\2\2\2\60\2\61\1\2\2\62\1\63\1\0"+
    "\1\64\4\2\1\65\2\66\1\2\1\67\1\2\1\70"+
    "\1\2\1\71";

  private static int [] zzUnpackAction() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\u0109\0\u013e\0\324"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\u0247\0\u027c\0\u02b1\0\u02e6"+
    "\0\u031b\0\u0350\0\u0385\0\u03ba\0\u03ef\0\u0424\0\324\0\324"+
    "\0\324\0\u0459\0\u048e\0\u04c3\0\u04f8\0\u052d\0\u0562\0\324"+
    "\0\324\0\324\0\324\0\324\0\324\0\324\0\324\0\324"+
    "\0\u0597\0\324\0\u05cc\0\u0601\0\u0636\0\u066b\0\u06a0\0\u06d5"+
    "\0\u070a\0\u073f\0\u0774\0\u07a9\0\u07de\0\u0813\0\u0848\0\u087d"+
    "\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986\0\u09bb\0\u09f0\0\u0a25"+
    "\0\324\0\u0a5a\0\237\0\324\0\324\0\324\0\324\0\324"+
    "\0\324\0\324\0\324\0\324\0\324\0\324\0\324\0\u0a8f"+
    "\0\u0ac4\0\u0af9\0\237\0\324\0\237\0\u0b2e\0\u0b63\0\u0b98"+
    "\0\324\0\u0bcd\0\237\0\u0c02\0\u0c37\0\u0c6c\0\u0ca1\0\237"+
    "\0\237\0\u0cd6\0\u0d0b\0\u0d40\0\237\0\u0d75\0\u0daa\0\u0ddf"+
    "\0\324\0\237\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3\0\u0ee8\0\324"+
    "\0\237\0\237\0\324\0\237\0\u0f1d\0\237\0\u0f52\0\u0f87"+
    "\0\324\0\237\0\324\0\237\0\u0fbc\0\324\0\237\0\324"+
    "\0\u0ff1\0\324\0\u1026\0\u105b\0\u1090\0\u10c5\0\324\0\324"+
    "\0\237\0\u10fa\0\237\0\u112f\0\237\0\u1164\0\237";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\3\1\4\1\5\1\6\1\5\1\7\2\10"+
    "\1\11\1\4\1\12\1\13\1\14\1\4\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\4\1\24\1\25"+
    "\6\4\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\3\5\6\51\2\5\52\51"+
    "\1\52\1\53\1\51\1\0\1\3\64\0\3\4\5\0"+
    "\3\4\1\0\12\4\1\0\7\4\120\0\1\54\3\0"+
    "\1\55\2\0\2\56\3\0\1\57\52\0\1\10\56\0"+
    "\3\4\5\0\3\4\1\0\10\4\1\60\1\4\1\61"+
    "\1\62\6\4\27\0\3\4\5\0\3\4\1\0\6\4"+
    "\1\63\3\4\1\0\7\4\54\0\1\64\37\0\3\4"+
    "\5\0\3\4\1\0\11\4\1\65\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\0\6\4\1\66\3\4\1\0"+
    "\7\4\27\0\3\4\5\0\3\4\1\0\12\4\1\0"+
    "\5\4\1\67\1\4\27\0\3\4\5\0\3\4\1\0"+
    "\2\4\1\70\5\4\1\71\1\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\0\6\4\1\72\3\4\1\0"+
    "\7\4\27\0\3\4\5\0\3\4\1\0\5\4\1\73"+
    "\4\4\1\0\1\4\1\74\5\4\27\0\3\4\5\0"+
    "\3\4\1\0\10\4\1\75\1\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\76\1\77\11\4\1\0\7\4"+
    "\37\0\1\100\24\0\1\101\27\0\3\4\5\0\1\102"+
    "\2\4\1\0\12\4\1\0\6\4\1\103\65\0\1\104"+
    "\70\0\1\105\65\0\1\106\67\0\1\107\64\0\1\110"+
    "\64\0\1\111\64\0\1\112\15\0\6\51\2\0\52\51"+
    "\2\0\1\51\17\0\1\113\1\114\10\0\1\115\30\0"+
    "\1\116\6\0\1\117\72\0\1\120\70\0\1\121\60\0"+
    "\1\122\53\0\3\4\5\0\3\4\1\0\12\4\1\0"+
    "\2\4\1\123\4\4\57\0\1\124\34\0\3\4\5\0"+
    "\3\4\1\0\12\4\1\0\1\4\1\125\5\4\27\0"+
    "\3\4\5\0\3\4\1\126\1\127\6\4\1\130\2\4"+
    "\1\0\7\4\37\0\1\131\12\0\1\132\41\0\3\4"+
    "\5\0\1\133\2\4\1\0\7\4\1\134\2\4\1\0"+
    "\7\4\27\0\3\4\5\0\3\4\1\0\12\4\1\0"+
    "\3\4\1\135\3\4\27\0\3\4\5\0\3\4\1\0"+
    "\6\4\1\136\3\4\1\0\7\4\27\0\3\4\5\0"+
    "\1\4\1\137\1\4\1\0\12\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\0\2\4\1\140\7\4\1\0"+
    "\7\4\27\0\3\4\5\0\3\4\1\0\3\4\1\141"+
    "\6\4\1\0\1\4\1\142\5\4\27\0\3\4\5\0"+
    "\3\4\1\143\1\144\11\4\1\0\7\4\27\0\3\4"+
    "\5\0\2\4\1\145\1\0\12\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\146\1\147\4\4\1\150\4\4"+
    "\1\0\7\4\52\0\1\151\41\0\3\4\5\0\3\4"+
    "\1\0\7\4\1\152\2\4\1\0\7\4\47\0\1\153"+
    "\44\0\3\4\5\0\3\4\1\0\4\4\1\154\5\4"+
    "\1\0\7\4\41\0\1\155\70\0\1\156\65\0\1\157"+
    "\70\0\1\160\41\0\3\4\5\0\3\4\1\0\7\4"+
    "\1\161\2\4\1\0\7\4\27\0\3\4\5\0\3\4"+
    "\1\0\7\4\1\162\2\4\1\0\7\4\52\0\1\163"+
    "\41\0\3\4\5\0\3\4\1\0\7\4\1\164\2\4"+
    "\1\0\7\4\27\0\3\4\5\0\3\4\1\0\6\4"+
    "\1\165\3\4\1\0\7\4\27\0\3\4\5\0\3\4"+
    "\1\0\12\4\1\0\1\4\1\166\5\4\27\0\3\4"+
    "\5\0\2\4\1\167\1\0\12\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\0\12\4\1\0\4\4\1\170"+
    "\2\4\51\0\1\171\42\0\3\4\5\0\3\4\1\0"+
    "\6\4\1\172\3\4\1\0\7\4\51\0\1\173\42\0"+
    "\3\4\5\0\3\4\1\0\6\4\1\174\3\4\1\0"+
    "\7\4\27\0\3\4\5\0\3\4\1\0\7\4\1\175"+
    "\2\4\1\0\7\4\45\0\1\176\46\0\3\4\5\0"+
    "\3\4\1\0\2\4\1\177\7\4\1\0\7\4\32\0"+
    "\1\200\100\0\1\201\50\0\1\202\61\0\3\4\5\0"+
    "\3\4\1\0\2\4\1\203\7\4\1\0\7\4\27\0"+
    "\3\4\5\0\3\4\1\0\11\4\1\204\1\0\7\4"+
    "\27\0\3\4\5\0\3\4\1\0\3\4\1\205\6\4"+
    "\1\0\7\4\27\0\3\4\5\0\3\4\1\0\11\4"+
    "\1\206\1\0\7\4\32\0\1\207\61\0\3\4\5\0"+
    "\3\4\1\210\1\211\11\4\1\0\7\4\27\0\3\4"+
    "\5\0\3\4\1\0\7\4\1\212\2\4\1\0\7\4"+
    "\27\0\3\4\5\0\3\4\1\0\12\4\1\0\5\4"+
    "\1\213\1\4\27\0\3\4\5\0\3\4\1\0\5\4"+
    "\1\214\4\4\1\0\7\4\27\0\3\4\5\0\3\4"+
    "\1\0\3\4\1\215\6\4\1\0\7\4\27\0\3\4"+
    "\5\0\3\4\1\0\10\4\1\216\1\4\1\0\7\4"+
    "\27\0\3\4\5\0\3\4\1\0\2\4\1\217\7\4"+
    "\1\0\7\4\26\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4505];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\1\1\11\2\1\1\11\2\1\1\0\10\1"+
    "\1\0\2\1\3\11\6\1\11\11\1\1\1\11\1\1"+
    "\4\0\1\1\1\0\2\1\1\0\11\1\1\0\1\1"+
    "\1\0\1\11\2\1\14\11\3\0\1\1\1\11\1\1"+
    "\1\0\2\1\1\11\1\0\10\1\1\0\2\1\1\0"+
    "\2\1\1\11\1\1\1\0\1\1\3\0\1\11\2\1"+
    "\1\11\5\1\1\11\1\1\1\11\2\1\1\11\1\1"+
    "\1\11\1\0\1\11\4\1\2\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[143];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
StringBuffer string=new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoH(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(TSHaskell.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol (TSHaskell.num, yycolumn, yyline, yytext());
            }
          case 58: break;
          case 2: 
            { return new Symbol (TSHaskell.id, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 3: 
            { /*errores lexicos*/
            }
          case 60: break;
          case 4: 
            { /*se ignora*/
            }
          case 61: break;
          case 5: 
            { return new Symbol (TSHaskell.suma, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 6: 
            { return new Symbol (TSHaskell.resta, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 7: 
            { return new Symbol (TSHaskell.mult, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 8: 
            { return new Symbol (TSHaskell.div, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 9: 
            { return new Symbol (TSHaskell.mayor, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 10: 
            { return new Symbol (TSHaskell.menor, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 11: 
            { return new Symbol (TSHaskell.igual, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 12: 
            { return new Symbol (TSHaskell.dolar, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 13: 
            { return new Symbol (TSHaskell.porcentaje, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 14: 
            { return new Symbol (TSHaskell.corchetea, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 15: 
            { return new Symbol (TSHaskell.corchetec, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 16: 
            { return new Symbol (TSHaskell.llavea, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 17: 
            { return new Symbol (TSHaskell.llavec, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 18: 
            { return new Symbol (TSHaskell.parentesisa, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 19: 
            { return new Symbol (TSHaskell.parentesisc, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 20: 
            { return new Symbol (TSHaskell.coma, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 21: 
            { string.append( yytext() );
            }
          case 78: break;
          case 22: 
            { yybegin(YYINITIAL); 
                                       return new Symbol(TSHaskell.cadena, 
                                       string.toString());
            }
          case 79: break;
          case 23: 
            { string.append('\\');
            }
          case 80: break;
          case 24: 
            { return new Symbol (TSHaskell.si, yycolumn, yyline, yytext());
            }
          case 81: break;
          case 25: 
            { return new Symbol (TSHaskell.concatenacion, yycolumn, yyline, yytext());
            }
          case 82: break;
          case 26: 
            { return new Symbol (TSHaskell.o, yycolumn, yyline, yytext());
            }
          case 83: break;
          case 27: 
            { return new Symbol (TSHaskell.y, yycolumn, yyline, yytext());
            }
          case 84: break;
          case 28: 
            { return new Symbol (TSHaskell.mayorigual, yycolumn, yyline, yytext());
            }
          case 85: break;
          case 29: 
            { return new Symbol (TSHaskell.menorigual, yycolumn, yyline, yytext());
            }
          case 86: break;
          case 30: 
            { return new Symbol (TSHaskell.igualacion, yycolumn, yyline, yytext());
            }
          case 87: break;
          case 31: 
            { return new Symbol (TSHaskell.distinto, yycolumn, yyline, yytext());
            }
          case 88: break;
          case 32: 
            { string.append('\r');
            }
          case 89: break;
          case 33: 
            { string.append('\t');
            }
          case 90: break;
          case 34: 
            { string.append('\n');
            }
          case 91: break;
          case 35: 
            { string.append('\"');
            }
          case 92: break;
          case 36: 
            { return new Symbol (TSHaskell.caracter, yycolumn, yyline, yytext());
            }
          case 93: break;
          case 37: 
            { return new Symbol (TSHaskell.max, yycolumn, yyline, yytext());
            }
          case 94: break;
          case 38: 
            { return new Symbol (TSHaskell.min, yycolumn, yyline, yytext());
            }
          case 95: break;
          case 39: 
            { return new Symbol (TSHaskell.sum, yycolumn, yyline, yytext());
            }
          case 96: break;
          case 40: 
            { return new Symbol (TSHaskell.par, yycolumn, yyline, yytext());
            }
          case 97: break;
          case 41: 
            { return new Symbol (TSHaskell.let, yycolumn, yyline, yytext());
            }
          case 98: break;
          case 42: 
            { return new Symbol (TSHaskell.fin, yycolumn, yyline, yytext());
            }
          case 99: break;
          case 43: 
            { return new Symbol (TSHaskell.asc, yycolumn, yyline, yytext());
            }
          case 100: break;
          case 44: 
            { return new Symbol (TSHaskell.desc, yycolumn, yyline, yytext());
            }
          case 101: break;
          case 45: 
            { return new Symbol (TSHaskell.decc, yycolumn, yyline, yytext());
            }
          case 102: break;
          case 46: 
            { return new Symbol (TSHaskell.succ, yycolumn, yyline, yytext());
            }
          case 103: break;
          case 47: 
            { return new Symbol (TSHaskell.entonces, yycolumn, yyline, yytext());
            }
          case 104: break;
          case 48: 
            { return new Symbol (TSHaskell.sino, yycolumn, yyline, yytext());
            }
          case 105: break;
          case 49: 
            { return new Symbol (TSHaskell.caso, yycolumn, yyline, yytext());
            }
          case 106: break;
          case 50: 
            { return new Symbol (TSHaskell.impr, yycolumn, yyline, yytext());
            }
          case 107: break;
          case 51: 
            { return new Symbol (TSHaskell.mod, yycolumn, yyline, yytext());
            }
          case 108: break;
          case 52: 
            { return new Symbol (TSHaskell.pot, yycolumn, yyline, yytext());
            }
          case 109: break;
          case 53: 
            { return new Symbol (TSHaskell.sqrt, yycolumn, yyline, yytext());
            }
          case 110: break;
          case 54: 
            { return new Symbol (TSHaskell.revers, yycolumn, yyline, yytext());
            }
          case 111: break;
          case 55: 
            { return new Symbol (TSHaskell.length, yycolumn, yyline, yytext());
            }
          case 112: break;
          case 56: 
            { return new Symbol (TSHaskell.product, yycolumn, yyline, yytext());
            }
          case 113: break;
          case 57: 
            { return new Symbol (TSHaskell.calcular, yycolumn, yyline, yytext());
            }
          case 114: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
