
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class TSHaskell {
  /* terminals */
  public static final int decc = 8;
  public static final int distinto = 36;
  public static final int suma = 25;
  public static final int resta = 26;
  public static final int mod = 2;
  public static final int par = 15;
  public static final int coma = 46;
  public static final int asc = 16;
  public static final int igual = 37;
  public static final int entonces = 20;
  public static final int calcular = 6;
  public static final int caracter = 48;
  public static final int let = 5;
  public static final int succ = 7;
  public static final int llavec = 43;
  public static final int llavea = 42;
  public static final int sum = 11;
  public static final int si = 19;
  public static final int length = 18;
  public static final int igualacion = 35;
  public static final int max = 10;
  public static final int menor = 32;
  public static final int porcentaje = 39;
  public static final int EOF = 0;
  public static final int parentesisc = 50;
  public static final int revers = 13;
  public static final int parentesisa = 49;
  public static final int error = 1;
  public static final int mayor = 31;
  public static final int pot = 4;
  public static final int menorigual = 34;
  public static final int id = 45;
  public static final int sqrt = 3;
  public static final int product = 12;
  public static final int caso = 23;
  public static final int y = 30;
  public static final int impr = 14;
  public static final int mult = 27;
  public static final int concatenacion = 24;
  public static final int fin = 21;
  public static final int mayorigual = 33;
  public static final int desc = 17;
  public static final int corchetec = 41;
  public static final int o = 29;
  public static final int corchetea = 40;
  public static final int dolar = 38;
  public static final int div = 28;
  public static final int num = 44;
  public static final int min = 9;
  public static final int cadena = 47;
  public static final int sino = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mod",
  "sqrt",
  "pot",
  "let",
  "calcular",
  "succ",
  "decc",
  "min",
  "max",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "asc",
  "desc",
  "length",
  "si",
  "entonces",
  "fin",
  "sino",
  "caso",
  "concatenacion",
  "suma",
  "resta",
  "mult",
  "div",
  "o",
  "y",
  "mayor",
  "menor",
  "mayorigual",
  "menorigual",
  "igualacion",
  "distinto",
  "igual",
  "dolar",
  "porcentaje",
  "corchetea",
  "corchetec",
  "llavea",
  "llavec",
  "num",
  "id",
  "coma",
  "cadena",
  "caracter",
  "parentesisa",
  "parentesisc"
  };
}

