/* The following code was generated by JFlex 1.6.1 */


package Analisis.HaskellTerminal;
import java_cup.runtime.*;
import Reportes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>src/Analisis/HaskellTerminal/LexicoHT.jflex</tt>
 */
public class LexicoHT implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
    50, 50, 50, 50, 50, 50, 50, 50, 50, 11,  6,  8,  9,  7, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    11, 49, 12, 50, 41, 39, 50,  5, 46, 47, 37, 35, 48, 36,  2, 38, 
     1,  1,  1,  1,  1,  1,  1,  1,  1,  1, 50, 50, 50, 40, 50, 50, 
    50, 26,  3, 25, 16, 24,  3, 33, 34, 29,  3,  3, 23, 14, 30, 15, 
    22, 19, 20, 18, 21, 27, 32,  3, 31,  3,  3, 42, 13, 43, 50,  4, 
    50, 26,  3, 25, 16, 24,  3, 33, 34, 29,  3,  3, 23, 14, 30, 15, 
    22, 19, 20, 18, 21, 27, 32,  3, 31,  3,  3, 44, 50, 45, 50, 50, 
    50, 50, 50, 50, 50,  8, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 
    50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\2\2\4\1\2\2\3"+
    "\1\0\6\3\1\0\1\3\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\2\6\0\1\23\1\0\1\3\1\0"+
    "\2\3\1\0\6\3\1\0\1\3\1\0\1\3\1\24"+
    "\1\25\1\1\1\26\3\0\1\23\1\27\2\30\1\0"+
    "\2\3\1\31\1\0\1\31\3\3\1\32\1\33\2\3"+
    "\2\34\1\0\1\3\3\0\2\35\1\36\2\37\4\3"+
    "\2\40\1\41\1\0\1\42\4\3\1\43\2\44\1\3"+
    "\1\45\1\3\1\46\1\3\1\47";

  private static int [] zzUnpackAction() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\314\0\146\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\u01cb\0\u01fe\0\u0231\0\u0264\0\u0297\0\u02ca"+
    "\0\u02fd\0\u0330\0\u0363\0\u0396\0\146\0\146\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\146\0\146"+
    "\0\146\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u0132"+
    "\0\146\0\u04fb\0\u052e\0\u0561\0\u0594\0\u05c7\0\u05fa\0\u062d"+
    "\0\u0660\0\u0693\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5"+
    "\0\u07f8\0\146\0\146\0\u03fc\0\146\0\u082b\0\u085e\0\u0891"+
    "\0\u0132\0\231\0\146\0\231\0\u08c4\0\u08f7\0\u092a\0\146"+
    "\0\u095d\0\231\0\u0990\0\u09c3\0\u09f6\0\231\0\231\0\u0a29"+
    "\0\u0a5c\0\146\0\231\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b"+
    "\0\146\0\231\0\231\0\146\0\231\0\u0b8e\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\146\0\231\0\146\0\u0c5a\0\146\0\u0c8d\0\u0cc0"+
    "\0\u0cf3\0\u0d26\0\146\0\146\0\231\0\u0d59\0\231\0\u0d8c"+
    "\0\231\0\u0dbf\0\231";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\3\1\5\1\6\1\7"+
    "\1\3\1\6\1\0\1\6\1\10\1\3\1\11\1\4"+
    "\1\12\1\13\1\14\1\4\1\15\1\4\1\16\1\17"+
    "\1\4\1\20\1\21\1\4\1\22\1\23\5\4\1\24"+
    "\1\25\1\26\1\27\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\1\37\1\40\1\41\1\42\1\3\1\0"+
    "\1\2\1\43\144\0\1\4\1\0\2\4\11\0\3\4"+
    "\1\0\12\4\1\0\6\4\20\0\6\44\5\0\3\44"+
    "\1\45\2\44\2\46\3\44\1\47\34\44\6\0\1\6"+
    "\54\0\14\50\1\51\1\52\45\50\1\0\1\4\1\0"+
    "\2\4\11\0\3\4\1\0\10\4\1\53\1\4\1\54"+
    "\1\55\5\4\21\0\1\4\1\0\2\4\11\0\3\4"+
    "\1\0\6\4\1\56\3\4\1\0\6\4\53\0\1\57"+
    "\30\0\1\4\1\0\2\4\11\0\3\4\1\0\11\4"+
    "\1\60\1\0\6\4\21\0\1\4\1\0\2\4\11\0"+
    "\3\4\1\0\6\4\1\61\3\4\1\0\6\4\21\0"+
    "\1\4\1\0\2\4\11\0\3\4\1\0\2\4\1\62"+
    "\5\4\1\63\1\4\1\0\6\4\21\0\1\4\1\0"+
    "\2\4\11\0\3\4\1\0\6\4\1\64\3\4\1\0"+
    "\6\4\21\0\1\4\1\0\2\4\11\0\3\4\1\0"+
    "\10\4\1\65\1\4\1\0\6\4\21\0\1\4\1\0"+
    "\2\4\11\0\3\4\1\66\1\67\11\4\1\0\6\4"+
    "\36\0\1\70\45\0\1\4\1\0\2\4\11\0\1\71"+
    "\2\4\1\0\12\4\1\0\6\4\63\0\1\72\100\0"+
    "\1\73\2\0\1\74\66\0\1\75\62\0\1\75\11\0"+
    "\1\76\50\0\1\75\15\0\1\77\44\0\1\75\11\0"+
    "\1\100\43\0\14\50\1\101\1\52\45\50\1\0\1\4"+
    "\1\0\2\4\11\0\3\4\1\0\12\4\1\0\2\4"+
    "\1\102\3\4\56\0\1\103\25\0\1\4\1\0\2\4"+
    "\11\0\3\4\1\0\12\4\1\0\1\4\1\104\4\4"+
    "\21\0\1\4\1\0\2\4\11\0\3\4\1\105\1\106"+
    "\6\4\1\107\2\4\1\0\6\4\36\0\1\110\12\0"+
    "\1\111\32\0\1\4\1\0\2\4\11\0\1\112\2\4"+
    "\1\0\7\4\1\113\2\4\1\0\6\4\21\0\1\4"+
    "\1\0\2\4\11\0\3\4\1\0\12\4\1\0\3\4"+
    "\1\114\2\4\21\0\1\4\1\0\2\4\11\0\1\4"+
    "\1\115\1\4\1\0\12\4\1\0\6\4\21\0\1\4"+
    "\1\0\2\4\11\0\3\4\1\0\2\4\1\116\7\4"+
    "\1\0\6\4\21\0\1\4\1\0\2\4\11\0\3\4"+
    "\1\0\3\4\1\117\6\4\1\0\1\4\1\120\4\4"+
    "\21\0\1\4\1\0\2\4\11\0\3\4\1\0\5\4"+
    "\1\121\4\4\1\0\6\4\51\0\1\122\32\0\1\4"+
    "\1\0\2\4\11\0\3\4\1\0\7\4\1\123\2\4"+
    "\1\0\6\4\46\0\1\124\35\0\1\4\1\0\2\4"+
    "\11\0\3\4\1\0\4\4\1\125\5\4\1\0\6\4"+
    "\40\0\1\126\66\0\1\127\63\0\1\130\66\0\1\131"+
    "\32\0\1\4\1\0\2\4\11\0\3\4\1\0\7\4"+
    "\1\132\2\4\1\0\6\4\21\0\1\4\1\0\2\4"+
    "\11\0\3\4\1\0\7\4\1\133\2\4\1\0\6\4"+
    "\51\0\1\134\32\0\1\4\1\0\2\4\11\0\3\4"+
    "\1\0\7\4\1\135\2\4\1\0\6\4\21\0\1\4"+
    "\1\0\2\4\11\0\3\4\1\0\6\4\1\136\3\4"+
    "\1\0\6\4\21\0\1\4\1\0\2\4\11\0\2\4"+
    "\1\137\1\0\12\4\1\0\6\4\21\0\1\4\1\0"+
    "\2\4\11\0\3\4\1\0\12\4\1\0\4\4\1\140"+
    "\1\4\21\0\1\4\1\0\2\4\11\0\3\4\1\0"+
    "\7\4\1\141\2\4\1\0\6\4\44\0\1\142\37\0"+
    "\1\4\1\0\2\4\11\0\3\4\1\0\2\4\1\143"+
    "\7\4\1\0\6\4\25\0\1\144\102\0\1\145\42\0"+
    "\1\146\56\0\1\4\1\0\2\4\11\0\3\4\1\0"+
    "\2\4\1\147\7\4\1\0\6\4\21\0\1\4\1\0"+
    "\2\4\11\0\3\4\1\0\11\4\1\150\1\0\6\4"+
    "\21\0\1\4\1\0\2\4\11\0\3\4\1\0\3\4"+
    "\1\151\6\4\1\0\6\4\21\0\1\4\1\0\2\4"+
    "\11\0\3\4\1\0\11\4\1\152\1\0\6\4\25\0"+
    "\1\153\56\0\1\4\1\0\2\4\11\0\3\4\1\154"+
    "\1\155\11\4\1\0\6\4\21\0\1\4\1\0\2\4"+
    "\11\0\3\4\1\0\7\4\1\156\2\4\1\0\6\4"+
    "\21\0\1\4\1\0\2\4\11\0\3\4\1\0\12\4"+
    "\1\0\5\4\1\157\21\0\1\4\1\0\2\4\11\0"+
    "\3\4\1\0\5\4\1\160\4\4\1\0\6\4\21\0"+
    "\1\4\1\0\2\4\11\0\3\4\1\0\3\4\1\161"+
    "\6\4\1\0\6\4\21\0\1\4\1\0\2\4\11\0"+
    "\3\4\1\0\10\4\1\162\1\4\1\0\6\4\21\0"+
    "\1\4\1\0\2\4\11\0\3\4\1\0\2\4\1\163"+
    "\7\4\1\0\6\4\20\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3570];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\1\1\11\2\1\1\11\4\1\1\0\6\1"+
    "\1\0\2\1\15\11\1\1\6\0\1\11\1\0\1\1"+
    "\1\0\2\1\1\0\6\1\1\0\1\1\1\0\1\1"+
    "\2\11\1\1\1\11\3\0\2\1\1\11\1\1\1\0"+
    "\2\1\1\11\1\0\10\1\1\11\1\1\1\0\1\1"+
    "\3\0\1\11\2\1\1\11\5\1\1\11\1\1\1\11"+
    "\1\0\1\11\4\1\2\11\7\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[115];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
StringBuffer string=new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public LexicoHT(java.io.Reader in) {
    this.zzReader = in;
  }



  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(TSHT.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { return new Symbol (TSHT.num, yycolumn, yyline, yytext());
            }
          case 40: break;
          case 2: 
            { TablaErrores.insertarError("Error lexico, caracter "+yytext()+" no pertenece al lenguaje.",yyline,yycolumn);
            }
          case 41: break;
          case 3: 
            { return new Symbol (TSHT.id, yycolumn, yyline, yytext().toLowerCase());
            }
          case 42: break;
          case 4: 
            { /*se ignora*/
            }
          case 43: break;
          case 5: 
            { return new Symbol (TSHT.suma, yycolumn, yyline, yytext());
            }
          case 44: break;
          case 6: 
            { return new Symbol (TSHT.resta, yycolumn, yyline, yytext());
            }
          case 45: break;
          case 7: 
            { return new Symbol (TSHT.mult, yycolumn, yyline, yytext());
            }
          case 46: break;
          case 8: 
            { return new Symbol (TSHT.div, yycolumn, yyline, yytext());
            }
          case 47: break;
          case 9: 
            { return new Symbol (TSHT.porcentaje, yycolumn, yyline, yytext());
            }
          case 48: break;
          case 10: 
            { return new Symbol (TSHT.igual, yycolumn, yyline, yytext());
            }
          case 49: break;
          case 11: 
            { return new Symbol (TSHT.dolar, yycolumn, yyline, yytext());
            }
          case 50: break;
          case 12: 
            { return new Symbol (TSHT.corchetea, yycolumn, yyline, yytext());
            }
          case 51: break;
          case 13: 
            { return new Symbol (TSHT.corchetec, yycolumn, yyline, yytext());
            }
          case 52: break;
          case 14: 
            { return new Symbol (TSHT.llavea, yycolumn, yyline, yytext());
            }
          case 53: break;
          case 15: 
            { return new Symbol (TSHT.llavec, yycolumn, yyline, yytext());
            }
          case 54: break;
          case 16: 
            { return new Symbol (TSHT.parentesisa, yycolumn, yyline, yytext());
            }
          case 55: break;
          case 17: 
            { return new Symbol (TSHT.parentesisc, yycolumn, yyline, yytext());
            }
          case 56: break;
          case 18: 
            { return new Symbol (TSHT.coma, yycolumn, yyline, yytext());
            }
          case 57: break;
          case 19: 
            { return new Symbol(TSHT.cadena, yycolumn, yyline, yytext().replace("\"", ""));
            }
          case 58: break;
          case 20: 
            { return new Symbol (TSHT.concatenacion, yycolumn, yyline, yytext());
            }
          case 59: break;
          case 21: 
            { return new Symbol (TSHT.acceso, yycolumn, yyline, yytext());
            }
          case 60: break;
          case 22: 
            { return new Symbol (TSHT.caracter, yycolumn, yyline, yytext().replace("'", ""));
            }
          case 61: break;
          case 23: 
            { return new Symbol (TSHT.max, yycolumn, yyline, yytext());
            }
          case 62: break;
          case 24: 
            { return new Symbol (TSHT.min, yycolumn, yyline, yytext());
            }
          case 63: break;
          case 25: 
            { return new Symbol (TSHT.sum, yycolumn, yyline, yytext());
            }
          case 64: break;
          case 26: 
            { return new Symbol (TSHT.par, yycolumn, yyline, yytext());
            }
          case 65: break;
          case 27: 
            { return new Symbol (TSHT.let, yycolumn, yyline, yytext());
            }
          case 66: break;
          case 28: 
            { return new Symbol (TSHT.asc, yycolumn, yyline, yytext());
            }
          case 67: break;
          case 29: 
            { return new Symbol (TSHT.desc, yycolumn, yyline, yytext());
            }
          case 68: break;
          case 30: 
            { return new Symbol (TSHT.decc, yycolumn, yyline, yytext());
            }
          case 69: break;
          case 31: 
            { return new Symbol (TSHT.succ, yycolumn, yyline, yytext());
            }
          case 70: break;
          case 32: 
            { return new Symbol (TSHT.impr, yycolumn, yyline, yytext());
            }
          case 71: break;
          case 33: 
            { return new Symbol (TSHT.mod, yycolumn, yyline, yytext());
            }
          case 72: break;
          case 34: 
            { return new Symbol (TSHT.pot, yycolumn, yyline, yytext());
            }
          case 73: break;
          case 35: 
            { return new Symbol (TSHT.sqrt, yycolumn, yyline, yytext());
            }
          case 74: break;
          case 36: 
            { return new Symbol (TSHT.revers, yycolumn, yyline, yytext());
            }
          case 75: break;
          case 37: 
            { return new Symbol (TSHT.length, yycolumn, yyline, yytext());
            }
          case 76: break;
          case 38: 
            { return new Symbol (TSHT.product, yycolumn, yyline, yytext());
            }
          case 77: break;
          case 39: 
            { return new Symbol (TSHT.calcular, yycolumn, yyline, yytext());
            }
          case 78: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
