
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analisis.HaskellTerminal;

/** CUP generated class containing symbol constants. */
public class TSHT {
  /* terminals */
  public static final int decc = 8;
  public static final int resta = 21;
  public static final int suma = 20;
  public static final int mod = 2;
  public static final int par = 15;
  public static final int coma = 33;
  public static final int asc = 16;
  public static final int igual = 25;
  public static final int acceso = 24;
  public static final int calcular = 6;
  public static final int caracter = 35;
  public static final int succ = 7;
  public static final int let = 5;
  public static final int llavec = 30;
  public static final int llavea = 29;
  public static final int sum = 11;
  public static final int length = 18;
  public static final int max = 10;
  public static final int porcentaje = 38;
  public static final int EOF = 0;
  public static final int parentesisc = 37;
  public static final int revers = 13;
  public static final int parentesisa = 36;
  public static final int error = 1;
  public static final int pot = 4;
  public static final int id = 32;
  public static final int product = 12;
  public static final int sqrt = 3;
  public static final int mult = 22;
  public static final int impr = 14;
  public static final int concatenacion = 19;
  public static final int desc = 17;
  public static final int corchetec = 28;
  public static final int corchetea = 27;
  public static final int dolar = 26;
  public static final int div = 23;
  public static final int num = 31;
  public static final int min = 9;
  public static final int cadena = 34;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "mod",
  "sqrt",
  "pot",
  "let",
  "calcular",
  "succ",
  "decc",
  "min",
  "max",
  "sum",
  "product",
  "revers",
  "impr",
  "par",
  "asc",
  "desc",
  "length",
  "concatenacion",
  "suma",
  "resta",
  "mult",
  "div",
  "acceso",
  "igual",
  "dolar",
  "corchetea",
  "corchetec",
  "llavea",
  "llavec",
  "num",
  "id",
  "coma",
  "cadena",
  "caracter",
  "parentesisa",
  "parentesisc",
  "porcentaje"
  };
}

